### ISSUE TITLE
UnboundLocalError: local variable 'batch_outputs' referenced before assignment

### ISSUE THREAD

**Issue by RDePlaen** [smousavi05/EQTransformer#9] opened 2020-09-08 18:02 UTC
```
Keras==2.4.3
tensorflow==2.2.0
Python 3.7.7
Ubuntu 18.04.5 LTS
```

When running the mseed_predictor on vertical-component Raspberry Shake data in Mexico, I come across this error which the last couple hours of googling told me that TensorFlow is probably to blame. Hopefully, someone has come across it before.

The full error message:
```
~/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer-0.1.55-py3.7.egg/EQTransformer/core/mseed_predictor.py in mseed_predictor(input_dir, input_model, stations_json, output_dir, detection_threshold, P_threshold, S_threshold, number_of_plots, plot_mode, loss_weights, loss_types, normalization_mode, batch_size, overlap, gpuid, gpu_limit)
    278             pred_generator = PreLoadGeneratorTest(meta["trace_start_time"], data_set, **params_pred)
    279 
--> 280             predD, predP, predS = model.predict_generator(pred_generator)
    281 
    282             detection_memory = []

~/anaconda3/envs/eqt/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

~/anaconda3/envs/eqt/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in predict_generator(self, generator, steps, callbacks, max_queue_size, workers, use_multiprocessing, verbose)
   1531         use_multiprocessing=use_multiprocessing,
   1532         verbose=verbose,
-> 1533         callbacks=callbacks)
   1534 
   1535   def _check_call_args(self, method_name):

~/anaconda3/envs/eqt/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     86       raise ValueError('{} is not supported in multi-worker mode.'.format(
     87           method.__name__))
---> 88     return method(self, *args, **kwargs)
     89 
     90   return tf_decorator.make_decorator(

~/anaconda3/envs/eqt/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1283             callbacks.on_predict_batch_end(step, {'outputs': batch_outputs})
   1284       callbacks.on_predict_end()
-> 1285     all_outputs = nest.map_structure_up_to(batch_outputs, concat, outputs)
   1286     return tf_utils.to_numpy_or_python_type(all_outputs)
   1287 

UnboundLocalError: local variable 'batch_outputs' referenced before assignment
```

**Comment by smousavi05** [comment] 2020-09-27 22:09
I recommend first run the examples in the jupyter notebooks before moving to your data. If it worked on the examples, I would double-check the input data. If you got the same error on the examples, reinstalling the package including the TensorFlow might help.

**Closed** 2020-11-15 18:28 UTC

**Comment by shicks-seismo** [comment] 2021-10-04 08:56
For anyone else having this problem, I found that this error was being caused by very short segments in my input mseed files (for me, a day file only had 30secs of data). I made a small change to mseed_predictor to skip such short-duration data.
